Pool oracle updates
yieldprotocol/yieldspace-tv pull request #82
Opened 2023-02-22 17:04 UTC by aaoferreira

Addressing audit findings

2023-03-10 11:13 UTC, alcueca requested changes
Could you please add the audit in an `audits` folder at the root?

2023-03-10 11:13 UTC, alcueca commented on src/oracle/PoolOracle.sol
> +        require(periodSize * granularity_ == windowSize_, "WINDOW_NOT_EVENLY_DIVISIBLE");
Wouldn't this be a bit clearer?

`require(windowSize_ % granularity_ == 0, "WINDOW_NOT_EVENLY_DIVISIBLE");`

2023-03-10 11:13 UTC, alcueca commented on src/oracle/PoolOracle.sol
> +            require(amount >> 192 == 0);
Are you checking that `amount <= type(uint192).max`?

2023-03-10 11:13 UTC, alcueca commented on src/oracle/PoolOracle.sol
> +            require(amount >> 192 == 0);
Also, the `require` should have some message

2023-03-10 11:13 UTC, alcueca commented on src/oracle/PoolOracle.sol
> +        returns (int128 price)
I think that you need natspec stating clearly which parameters and return values are 64.64

2023-03-10 11:13 UTC, alcueca commented on src/oracle/PoolOracle.sol
> +            result = (amount << 64) / uint128(price); // result = amount / price
If the `<< 64` is intended to convert `amount` to 64.64, then it would be clearer to use `Math64x64.fromUint()`

2023-03-10 20:09 UTC, aaoferreira commented
>Could you please add the audit in an audits folder at the root?
We're waiting for the final report from ABDK, as soon as it's available I'll update the PR

2023-03-10 20:36 UTC, aaoferreira commented on src/oracle/PoolOracle.sol
> +            require(amount >> 192 == 0);
This is a direct recommendation from ADBK's audit regarding gas savings. These requires already exists in their framework and are just being surfaced, so they're left as-is

2023-03-10 20:36 UTC, aaoferreira commented on src/oracle/PoolOracle.sol
> +            result = (amount << 64) / uint128(price); // result = amount / price
Also a direct recommendation from ADBK's audit regarding gas savings. This provides a one operation to scale and divide and avoiding having to do another casting before dividing.

2023-03-13 06:27 UTC, alcueca commented on src/oracle/PoolOracle.sol
> +            require(amount >> 192 == 0);
Cool, then please just add a comment saying so to redcue the head-scratching. Not everyone is going to be as smart as the ABDK guys.

2023-03-13 06:28 UTC, alcueca commented on src/oracle/PoolOracle.sol
> +            result = (amount << 64) / uint128(price); // result = amount / price
Optimizooooors.

I like to reduce the surprise factor in code. So a little comment there, please.

2023-03-13 06:29 UTC, alcueca approved these changes
Please add those comments before you merge, and the audit in a later PR, please.

2023-03-13 06:30 UTC, alcueca commented
Actually, put a comment at the top like:
`/// Audited by ABDK 13/03/23, report pending.`

2023-03-22 16:02 UTC, aaoferreira commented
addressed the requests and will hold on the public announcement on our side to add the audit and merge this

2023-03-23 11:33 UTC, merged